### ISSUE TITLE
URL is set to "localhost"

### ISSUE THREAD

**Issue by gilbitron** [janhenkgerritsen/codeception-laravel5#11]
In my `acceptance.suite.yml` I have the following config:

```
class_name: AcceptanceTester
modules:
    enabled: [PhpBrowser, AcceptanceHelper, Laravel5]
    config:
        PhpBrowser:
            url: 'http://mysite.dev'
```

If I don't use the Laravel5 module the URL is correctly set to `http://mysite.dev` and tests work. However once I enable the Laravel5 module all requests seem to be from `localhost`, which means my tests fail on redirect because I am using subdomains (`Maximum function nesting level of '200' reached, aborting!`). My `url` in app/config.php is set correctly. 

Just to clarify my debug output looks like:
```
[Response] 200
[Page] http://localhost/login
[Cookies] []
[Headers] {...}
```

When it should look like:
```
[Response] 200
[Page] http://test.mysite.dev/login
[Cookies] []
[Headers] {...}
```

Any ideas why it would be overriding the PhpBrowser config?
