### ISSUE TITLE
404 on amOnRoute() using Route::group(['domain' => 'example.com'])

### ISSUE THREAD

**Issue by foxted** [janhenkgerritsen/codeception-laravel5#13]
Hi,

I have an issue using this package when using domain routes with Laravel 5. 

For example, I have my authentication on my main domain only, so I have defined a login page like so: 

```php
Route::group( [  'prefix' => 'auth', 'namespace' => 'Auth', 'domain' => 'example.com' ], function ()
{
    Route::get( 'login', ['as' => 'auth.login', 'uses' => function(){
        return 'Hello world!';
    }] );
});
```

And my LoginCept file looks like this: 

```php
$I = new BackendTester($scenario);
$I->wantTo('login in the application');

$I->amOnRoute('auth.login');
$I->seeResponseCodeIs(200);
```

And this is my codeception suite config:

```yaml
class_name: BackendTester
modules:
    enabled: [BackendHelper, Filesystem, Laravel5]
    config:
        Laravel5:
            environment_file: .env.testing
```
Here is the error I get when running the test:

```
---------
1) Failed to login in the application in Auth/LoginCept (/Users/<user>/Sites/example.com/tests/backend/Auth/LoginCept.php)
Couldn't see response code is 200:
Failed asserting that 404 matches expected 200.

Scenario Steps:
2. I see response code is 200
1. I am on route "auth.login"


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
---------
```

If I remove the parameter `'domain'=>'example.com'` from my `Route::group`, everything works fine.

Any idea?

Thanks!
