### ISSUE TITLE
Doesn't rollback

### ISSUE THREAD

**Issue by Radostin** [janhenkgerritsen/codeception-laravel5#20]
The module doesn't want to rollback the transactions in between the tests.

I have tried different options:

Integration test suite:
```
class_name: IntegrationTester
modules:
    enabled: [IntegrationHelper, Laravel5, Db]
    Db:
        dsn: 'mysql:host=localhost;dbname=fde_test'
        user: 'homestead'
        password: 'secret'
        dump: 'tests/_data/dump.sql'
        populate: true
        cleanup: true
    Laravel5:
        cleanup: true
```

I've even have:

```
 protected function _before()
    {
        DB::beginTransaction();
    }

    protected function _after()
    {
        DB::rollBack();
    }
```

Which doesn't really help, anyway!
